//#define HIT_HUNTER                    1
#define GAME_TURTLE                   1
#define GAME_KEYBOARD_ENABLED         1
#define GAME_RECORDING                1
//#define GAME_ONE_BITPLANE_SPRITE_MASK 1
#define GAME_STARS                    1
#define GAME_HISCORE_SAVE_ENABLE      1
//#define GAME_BLITTER_WAIT_DEBUG       1
#define GAME_TRIPLE_BUFFER           1
#define GAME_COMPRESS_LEVEL_DATA    1
